name: Deploy package to PyPI

on:
  release:
    types: [published]
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'PyPI_workflow_dev'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install --upgrade setuptools wheel pytest flake8 black mypy ruff setuptools_scm

    # - name: Lint with ruff
    #   run: ruff check . .

    # - name: Type check with mypy
    #   run: mypy .

    # - name: Run tests
    #   run: pytest --cov=css

    - name: Build wheel
      run: python setup.py sdist bdist_wheel

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.6
      with:
        password: ${{ secrets.PYPI_TEST_TOKEN }}
        repository-url: https://test.pypi.org/legacy/